apiVersion: v1
kind: Namespace
metadata:
  name: avalanche
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 1
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: avalanche
        image: quay.io/prometheuscommunity/avalanche:latest
        args:
        # Example metric distribution. See cmd/mtypes on how to generate different distributions
        # based on real scrape targets.
        - "--gauge-metric-count=16"
        - "--counter-metric-count=28"
        - "--histogram-metric-count=2"
        - "--histogram-metric-bucket-count=10" # Does not count +Inf
        - "--native-histogram-metric-count=0"
        - "--summary-metric-count=5" # One metric gives 2 series.
        - "--summary-metric-objective-count=2" # One metric gives 2 series.
        - "--series-count=10"
        - "--value-interval=300" # Changes values every 5m
        - "--series-interval=3600" # 1h series churn.
        - "--metric-interval=0"
        - "--port=9001"
        ports:
        - containerPort: 9001
---
#create service avalanche-svc
apiVersion: v1
kind: Service
metadata:
  name: avalanche-svc
  namespace: avalanche
  labels:
    app: avalanche
spec:
  ports:
  # the port that this service should serve on
  - port: 9001
    targetPort: 9001
    name: http-avalanche
  type: ClusterIP
  clusterIP: None
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: avalanche
