version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run: make docker-build

  publish-latest:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "${QUAY_PASSWORD}" | docker login -u "${QUAY_USERNAME}" --password-stdin quay.io
      - run: make docker-publish
      - run: DOCKER_TAG=latest make docker-publish

  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "${QUAY_PASSWORD}" | docker login -u "${QUAY_USERNAME}" --password-stdin quay.io
      - run: DOCKER_TAG=$CIRCLE_TAG make docker-publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            # Tags filter is needed to run releases.
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
