---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.17.1

executors:
  # Whenever the Go version is updated here, .promu.yml should also be updated.
  golang:
    docker:
      - image: quay.io/prometheus/golang-builder:1.22-base

jobs:
  test:
    executor: golang

    steps:
      - prometheus/setup_environment
      - run: make
      - prometheus/store_artifact:
          file: avalanche
      - run: git diff --exit-code

workflows:
  version: 2
  avalanche:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - prometheus/build:
          name: build
          filters:
            tags:
              only: /.*/
      - prometheus/publish_main:
          context: org-context
          docker_hub_organization: prometheuscommunity
          quay_io_organization: prometheuscommunity
          requires:
            - test
            - build
          filters:
            branches:
              only: main
      - prometheus/publish_release:
          context: org-context
          docker_hub_organization: prometheuscommunity
          quay_io_organization: prometheuscommunity
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
